/**
 * Full-app backup (localStorage + IndexedDB photos) and restore.
 */
(function (global) {
  function collectLocalStorage() {
    const ls = {};
    try {
      for (let i = 0; i < global.localStorage.length; i++) {
        const k = global.localStorage.key(i);
        if (k) ls[k] = global.localStorage.getItem(k);
      }
    } catch (e) {
      throw new Error('Could not read saved data.');
    }
    return ls;
  }

  function buildPayload(ls, photoRows) {
    return {
      format: 'etm-checklist-backup',
      formatVersion: 1,
      exportedAt: new Date().toISOString(),
      app: 'ETM Checklist',
      note:
        'Restore from the ETM Checklist home screen: Save all data / Replace all data. Do not edit this file by hand unless you know what you are doing.',
      localStorage: ls,
      indexedDbPhotoRows: photoRows
    };
  }

  function triggerDownload(jsonString, filename) {
    const blob = new Blob([jsonString], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = global.document.createElement('a');
    a.href = url;
    a.download = filename;
    global.document.body.appendChild(a);
    a.click();
    a.remove();
    global.setTimeout(function () {
      URL.revokeObjectURL(url);
    }, 2500);
  }

  /**
   * @returns {Promise<void>}
   */
  function downloadFullBackup(statusFn) {
    statusFn = typeof statusFn === 'function' ? statusFn : function () {};
    const ls = collectLocalStorage();
    statusFn('Preparing backup (photos may take a moment)…');
    const photoP =
      global.EtmMediaDB && global.EtmMediaDB.exportAllPhotoRowsSerialized
        ? global.EtmMediaDB.exportAllPhotoRowsSerialized().catch(function () {
            return [];
          })
        : Promise.resolve([]);
    return photoP.then(function (photoRows) {
      const payload = buildPayload(ls, photoRows);
      const json = JSON.stringify(payload);
      triggerDownload(json, 'etm-checklist-full-backup-' + Date.now() + '.json');
      statusFn('Backup downloaded.');
    });
  }

  function validateBackup(raw) {
    if (!raw || typeof raw !== 'object') {
      return { ok: false, error: 'This file is not valid JSON.' };
    }
    if (raw.format !== 'etm-checklist-backup') {
      return { ok: false, error: 'This file is not an ETM Checklist backup.' };
    }
    if (Number(raw.formatVersion) !== 1) {
      return { ok: false, error: 'This backup version is not supported. Update the app and try again.' };
    }
    const ls = raw.localStorage;
    if (!ls || typeof ls !== 'object' || Array.isArray(ls)) {
      return { ok: false, error: 'Backup is missing saved settings (localStorage).' };
    }
    let rows = raw.indexedDbPhotoRows;
    if (rows == null) rows = [];
    if (!Array.isArray(rows)) {
      return { ok: false, error: 'Backup has invalid photo data.' };
    }
    return {
      ok: true,
      data: {
        format: raw.format,
        formatVersion: 1,
        localStorage: ls,
        indexedDbPhotoRows: rows
      }
    };
  }

  /**
   * Replaces all local app data with backup contents. Caller should confirm first.
   * @returns {Promise<void>}
   */
  function replaceAllDataFromBackup(backupData) {
    const M = global.EtmMediaDB;
    if (!M || !M.importSerializedPhotoRows) {
      return Promise.reject(new Error('Photo database is not available in this browser.'));
    }
    const rows = backupData.indexedDbPhotoRows || [];
    return M.importSerializedPhotoRows(rows).then(function () {
      const ls = backupData.localStorage || {};
      const toRemove = [];
      for (let i = 0; i < global.localStorage.length; i++) {
        const k = global.localStorage.key(i);
        if (k && !Object.prototype.hasOwnProperty.call(ls, k)) {
          toRemove.push(k);
        }
      }
      toRemove.forEach(function (k) {
        global.localStorage.removeItem(k);
      });
      Object.keys(ls).forEach(function (k) {
        const v = ls[k];
        global.localStorage.setItem(k, v == null ? '' : String(v));
      });
    });
  }

  global.EtmBackup = {
    collectLocalStorage: collectLocalStorage,
    buildPayload: buildPayload,
    downloadFullBackup: downloadFullBackup,
    validateBackup: validateBackup,
    replaceAllDataFromBackup: replaceAllDataFromBackup
  };
})(typeof window !== 'undefined' ? window : this);
